-- Build configuration for l3build (https://ctan.org/pkg/l3build)
--
-- Commands
--   l3build check                 run docsync and all regression tests in testfiles/ on all engines
--   l3build check <name>          run a single test (testfiles/<name>.lvt)
--   l3build check -e luatex       run the tests on one engine only
--   l3build save <name>           (re)create the reference log testfiles/<name>.tlg
--   l3build save -e luatex <name> (re)create an engine-specific log testfiles/<name>.luatex.tlg
--   l3build docsync               only run the documentation/test coverage check (see below)
--
-- Day-to-day use
--   * Run `l3build check` before committing. It takes a few seconds.
--   * A failing test leaves a diff in build/test/<name>.<engine>.diff (expected vs. actual log).
--     If the change is a regression, fix the package. If it is intended, run
--     `l3build save <name>`, review the diff of the .tlg in git and commit it with the change.
--   * namestyle.lvt shows typeset boxes, which depend on the engine's fonts, so it has one
--     .tlg per engine: after an intended change, save it for every engine (pdftex is the
--     default engine and writes namestyle.tlg):
--       l3build save namestyle && l3build save -e luatex namestyle
--     All other tests are engine independent and share one .tlg; keep it that way by putting
--     font-dependent output only into namestyle.lvt.
--   * New command: add it to the documentation and to the "public commands" list in
--     testfiles/api-commands.lvt (plus a smoke test of its call forms); docsync fails until then.
--   * New option or option value: document it in the Package Options section (values in the
--     "... options: \texttt{a}, \texttt{b} and \texttt{c}." sentence) and add a key=value
--     line to testfiles/options-values.lvt; docsync fails until then.
--   * New warning or error: add a case to testfiles/messages.lvt.
--   * A TeX Live update (e.g. a new pgf version) can change a log without any change in this
--     package; check the diff and re-save.
--   * Test helpers (\SHOWOPTIONS, \SHOWSTYLE, \SHOWID, ...) live in
--     testfiles/support/argumentation-test.tex.

module = "argumentation"

sourcefiles  = {"argumentation.sty"}
installfiles = {"argumentation.sty"}
typesetfiles = {"argumentation-doc.tex"}

checkengines = {"pdftex", "luatex"}
checkruns    = 2   -- api-commands resolves an \afref

--------------------------------------------------------------------------------
-- docsync: keep package, documentation and tests in agreement
--   * every public command of the package is documented
--   * every public command is listed in the "public commands" test of api-commands.lvt
--   * the options described in the "Package Options" section match the package's
--     /argumentation keys, including the listed choice values
--   * every choice value is exercised in options-values.lvt
--------------------------------------------------------------------------------

-- /argumentation keys that are not package options
local internal_keys = {["attack tip"] = true}

local function readfile(name)
  local f = assert(io.open(name, "rb"))
  local s = f:read("a")
  f:close()
  return s
end

local function set_add(set, key) set[key] = true end

local function sorted_keys(set)
  local t = {}
  for k in pairs(set) do t[#t + 1] = k end
  table.sort(t)
  return t
end

-- Public commands: \NewDocumentCommand, \newcommand and \providecommand without @,
-- plus the <env>ref macros generated by \newafenvironment
local function package_commands(sty)
  local cmds = {}
  for name in sty:gmatch("\\NewDocumentCommand%s*{%s*\\(%a+)%s*}") do set_add(cmds, name) end
  for name in sty:gmatch("\\newcommand%s*{\\(%a+)}") do set_add(cmds, name) end
  for name in sty:gmatch("\\providecommand%s*{\\(%a+)}") do set_add(cmds, name) end
  for env in sty:gmatch("\n%s*\\newafenvironment{(%a+)}") do set_add(cmds, env .. "ref") end
  return cmds
end

-- Commands mentioned in the documentation via \cs{...}, \cs[..]{...}, \cmd\... or \verb|\...|
local function documented_commands(doc)
  local cmds = {}
  for name in doc:gmatch("\\cs{(%a+)") do set_add(cmds, name) end
  for name in doc:gmatch("\\cs%[[^]]*%]{(%a+)") do set_add(cmds, name) end
  for name in doc:gmatch("\\cmd\\(%a+)") do set_add(cmds, name) end
  for _, name in doc:gmatch("\\verb(.)\\(%a+)") do set_add(cmds, name) end
  return cmds
end

-- Commands listed in the "public commands" test
local function tested_commands(lvt)
  local block = lvt:match("\\TEST{public commands}(.-)\\TEST") or ""
  local cmds = {}
  for name in block:gmatch("\\CHECKDEFINED\\(%a+)") do set_add(cmds, name) end
  return cmds
end

-- Package options: {key = {value = true, ...}} from the \pgfkeys{/argumentation/.cd, ...} blocks
local function package_options(sty)
  local opts = {}
  for block in sty:gmatch("\\pgfkeys{/argumentation/%.cd,(.-)\n%s*}") do
    for key in block:gmatch("%f[%a](%a[%a ]-)/%.is choice") do opts[key] = opts[key] or {} end
    for key in block:gmatch("%f[%a](%a[%a ]-)/%.initial") do
      if not internal_keys[key] then opts[key] = opts[key] or {} end
    end
    for key, value in block:gmatch("%f[%a](%a[%a ]-)/(%a+)/%.code") do
      if opts[key] then set_add(opts[key], value) end
    end
  end
  return opts
end

-- Documented options: the \item[key] entries of the "Package Options" section, with
-- the values listed in their "... options: \texttt{a}, \texttt{b} and \texttt{c}." sentence
local function documented_options(doc)
  local section = doc:match("\\section{Package Options}(.-)\\section") or ""
  local list = section:match("\\begin{description}(.-)\\end{description}") or ""
  local opts = {}
  local items, pos = {}, list:find("\\item[", 1, true)
  while pos do
    local next_pos = list:find("\\item[", pos + 1, true)
    items[#items + 1] = list:sub(pos + #"\\item[", (next_pos or #list + 1) - 1)
    pos = next_pos
  end
  for _, item in ipairs(items) do
    local key, text = item:match("^([^]]+)%](.*)")
    opts[key] = {}
    local sentence = text:match("options[%a ]*:(.-)%.%s*\n") or ""
    for value in sentence:gmatch("\\texttt{(%a+)}") do set_add(opts[key], value) end
  end
  return opts
end

local function is_boolean(values)
  local v = sorted_keys(values)
  return #v == 2 and v[1] == "false" and v[2] == "true"
end

function docsync()
  local sty = readfile("argumentation.sty")
  local doc = readfile("argumentation-doc.tex")
  local api_lvt = readfile(testfiledir .. "/api-commands.lvt")
  local values_lvt = readfile(testfiledir .. "/options-values.lvt")
  local problems = {}
  local function problem(msg) problems[#problems + 1] = msg end

  local pkg_cmds = package_commands(sty)
  local doc_cmds = documented_commands(doc)
  local test_cmds = tested_commands(api_lvt)
  for _, name in ipairs(sorted_keys(pkg_cmds)) do
    if not doc_cmds[name] then problem("command \\" .. name .. " is not documented") end
    if not test_cmds[name] then problem("command \\" .. name .. " is missing from the public commands test in api-commands.lvt") end
  end
  for _, name in ipairs(sorted_keys(test_cmds)) do
    if not pkg_cmds[name] then problem("api-commands.lvt checks \\" .. name .. ", which the package does not define") end
  end

  local pkg_opts = package_options(sty)
  local doc_opts = documented_options(doc)
  for _, key in ipairs(sorted_keys(pkg_opts)) do
    local values = pkg_opts[key]
    if not doc_opts[key] then
      problem("option '" .. key .. "' is not documented in the Package Options section")
    elseif not is_boolean(values) then
      for _, value in ipairs(sorted_keys(values)) do
        if next(doc_opts[key]) and not doc_opts[key][value] then
          problem("value '" .. key .. "=" .. value .. "' is not listed in the documentation")
        end
        if not values_lvt:find(key .. "=" .. value, 1, true) then
          problem("value '" .. key .. "=" .. value .. "' is not tested in options-values.lvt")
        end
      end
      for _, value in ipairs(sorted_keys(doc_opts[key])) do
        if not values[value] then
          problem("documented value '" .. key .. "=" .. value .. "' is not defined by the package")
        end
      end
    end
  end
  for _, key in ipairs(sorted_keys(doc_opts)) do
    if not pkg_opts[key] then problem("documented option '" .. key .. "' is not defined by the package") end
  end

  if #problems == 0 then
    print("docsync: package, documentation and tests agree")
    return 0
  end
  print("docsync: " .. #problems .. " problem(s) found")
  for _, msg in ipairs(problems) do print("  - " .. msg) end
  return 1
end

target_list.docsync = {
  func = docsync,
  desc = "Checks that commands and options agree between package, docs and tests",
}

-- Also run it as part of `l3build check`
function checkinit_hook() return docsync() end
