name: Build check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile documentation
        uses: xu-cheng/latex-action@v3
        with:
          root_file: argumentation-doc.tex
